[package]
name = "my_core_utils"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
[[bin]]
path = "src/main.rs"
name = "my_core_utils"

[dependencies]
clap = { version = "4.5.19" }
clap_derive = "4.5.18"